################################################################################
# Name:        Particle Simulator Settings
# Version:     1.0
# Date:        2014
# Author:      Rohin Gosling
# Description: Application settings for the Particle Simulator demo.
################################################################################

#-------------------------------------------------------------------------------
# Application
#-------------------------------------------------------------------------------

Application.Name            = Particle Simulator
Application.Version.Major   = 1
Application.Version.Minor   = 2
Application.Screen.Width    = 1920
Application.Screen.Height   = 1080
Application.Logging.Enabled = true

#-------------------------------------------------------------------------------
# Menu Background Images
#-------------------------------------------------------------------------------

Menu.Background.Main         = Demo/ParticleDemo/Resources/Images/Background/background-menu-title-1920x1080.png
Menu.Background.Settings     = Demo/ParticleDemo/Resources/Images/Background/background-menu-title-settings-1920x1080.png
Menu.Background.Instructions = Demo/ParticleDemo/Resources/Images/Background/background-menu-title-instructions-1920x1080.png
Menu.Background.About        = Demo/ParticleDemo/Resources/Images/Background/background-menu-title-about-1920x1080.png

#-------------------------------------------------------------------------------
# Menu Button Images
#-------------------------------------------------------------------------------

Menu.Button.Image.Up           = Demo/ParticleDemo/Resources/Images/Buttons/button-up.png
Menu.Button.Image.UpSelected   = Demo/ParticleDemo/Resources/Images/Buttons/button-up-selected.png
Menu.Button.Image.Down         = Demo/ParticleDemo/Resources/Images/Buttons/button-down.png
Menu.Button.Image.DownSelected = Demo/ParticleDemo/Resources/Images/Buttons/button-down-selected.png
Menu.Button.Image.Disabled     = Demo/ParticleDemo/Resources/Images/Buttons/button-disabled.png
Menu.Button.Image.Shadow       = Demo/ParticleDemo/Resources/Images/Buttons/button-shadow.png
Menu.Button.Shadow.Offset.X    = 6
Menu.Button.Shadow.Offset.Y    = 6
Menu.Button.Shadow.Opacity     = 0.1

#-------------------------------------------------------------------------------
# Menu Button Font
#-------------------------------------------------------------------------------

Menu.Button.Font.Name             = Anita  Semi-square
Menu.Button.Font.Size             = 30
Menu.Button.Font.Color.Selected   = 255,255,255
Menu.Button.Font.Color.Unselected = 128,128,128
Menu.Button.Font.Color.Disabled   = 64,64,64

#-------------------------------------------------------------------------------
# Menu Button Layout
#-------------------------------------------------------------------------------

Menu.Button.Layout.X         = 480
Menu.Button.Layout.Y.Start   = 290
Menu.Button.Layout.Y.Spacing = 140

#-------------------------------------------------------------------------------
# Menu Text Box
#-------------------------------------------------------------------------------

Menu.TextBox.Font.Name    = Courier New
Menu.TextBox.Font.Size    = 18
Menu.TextBox.Font.Color   = 255,255,255
Menu.TextBox.Text.Opacity = 0.5
Menu.TextBox.X            = 200
Menu.TextBox.Y            = 280
Menu.TextBox.Width        = 1520
Menu.TextBox.Height       = 500

#-------------------------------------------------------------------------------
# Menu Text Files
#-------------------------------------------------------------------------------

Menu.Text.Instructions           = Demo/ParticleDemo/Resources/Text/instructions.txt
Menu.Text.Instructions.Alignment = left
Menu.Text.About                  = Demo/ParticleDemo/Resources/Text/about.txt
Menu.Text.About.Alignment        = center

#-------------------------------------------------------------------------------
# Particle Count Defaults
#-------------------------------------------------------------------------------

Particle.Count.Red.Default    = 6
Particle.Count.Green.Default  = 3
Particle.Count.Blue.Default   = 1
Particle.Count.Yellow.Default = 3
Particle.Count.Min            = 0
Particle.Count.Max            = 32

#-------------------------------------------------------------------------------
# Simulation Background
#-------------------------------------------------------------------------------

Simulation.Background = Demo/ParticleDemo/Resources/Images/Background/background-simulator-1920x1080.png

#-------------------------------------------------------------------------------
# Sprite Images
#-------------------------------------------------------------------------------

Sprite.Red      = Demo/ParticleDemo/Resources/Images/Sprites/glass-sphere-red-256x256.png
Sprite.Green    = Demo/ParticleDemo/Resources/Images/Sprites/glass-sphere-green-256x256.png
Sprite.Blue     = Demo/ParticleDemo/Resources/Images/Sprites/glass-sphere-blue-256x256.png
Sprite.Yellow   = Demo/ParticleDemo/Resources/Images/Sprites/glass-sphere-yellow-256x256.png
Sprite.Selected = Demo/ParticleDemo/Resources/Images/Sprites/glass-sphere-clear-256x256.png
Sprite.Shadow   = Demo/ParticleDemo/Resources/Images/Sprites/glass-sphere-shadow-256x256.png

#Sprite.Red      = Demo/ParticleDemo/Resources/Images/Sprites/light-red-250x250.png
#Sprite.Green    = Demo/ParticleDemo/Resources/Images/Sprites/light-green-250x250.png
#Sprite.Blue     = Demo/ParticleDemo/Resources/Images/Sprites/light-blue-250x250.png
#Sprite.Yellow   = Demo/ParticleDemo/Resources/Images/Sprites/light-yellow-250x250.png
#Sprite.Selected = Demo/ParticleDemo/Resources/Images/Sprites/light-white-250x250.png
#Sprite.Shadow   = Demo/ParticleDemo/Resources/Images/Sprites/light-beam-250x250.png


#-------------------------------------------------------------------------------
# Physics
#-------------------------------------------------------------------------------

Physics.Gravity.Constant       = 0.0001
Physics.Repulsion.Constant     = 4.0
Physics.Softening.Epsilon      = 0.009
Physics.Friction.Coefficient   = 0.99
Physics.Friction.Anisotropic   = 0.99
Physics.Elasticity.Coefficient = 0.9
Physics.User.Acceleration      = 1.0
Physics.Boundary.Collision     = true
Physics.Collision.Iterations   = 4

Physics.Gravity.Enabled        = true
Physics.Repulsion.Enabled      = true
Physics.Friction.Enabled       = true
Physics.Elasticity.Enabled     = true

#-------------------------------------------------------------------------------
# Particle Group Properties
#-------------------------------------------------------------------------------

Particle.Mass.Red    = 8.0
Particle.Mass.Green  = 4.0
Particle.Mass.Blue   = 2.0
Particle.Mass.Yellow = 1.0

Particle.Radius.Red    = 0.032
Particle.Radius.Green  = 0.016
Particle.Radius.Blue   = 0.008
Particle.Radius.Yellow = 0.004


#-------------------------------------------------------------------------------
# Trails
#-------------------------------------------------------------------------------

Trail.Color.Red      = 255,128,128
Trail.Color.Green    = 128,255,128
Trail.Color.Blue     = 128,128,255
Trail.Color.Yellow   = 255,255,128
Trail.Color.Selected = 128,128,128
Trail.Depth          = 1000
Trail.Opacity.Head   = 0.03
Trail.Opacity.Tail   = 0.0
Trail.Thickness      = 4
Trail.Visible        = true

#-------------------------------------------------------------------------------
# Wireframe
#-------------------------------------------------------------------------------

Wireframe.Visible = false

#-------------------------------------------------------------------------------
# Shadow (Simulation Sprites)
#-------------------------------------------------------------------------------

Shadow.Offset.X = 0.0
Shadow.Offset.Y = 0.025
Shadow.Opacity  = 0.4
Shadow.Scale    = 1.4

#-------------------------------------------------------------------------------
# Projection
#-------------------------------------------------------------------------------

Projection.Zoom = 1.0

#-------------------------------------------------------------------------------
# HUD (Heads Up Display)
#-------------------------------------------------------------------------------

Hud.Font.Name   = Courier New
Hud.Font.Size   = 14
Hud.Font.Color  = 0,255,0
Hud.Position.X  = 10.0
Hud.Position.Y  = 10.0

#-------------------------------------------------------------------------------
# Initial Particle Velocity
#-------------------------------------------------------------------------------

Initial.Velocity.Min = 0.02
Initial.Velocity.Max = 0.04
